language: python

python:
- '3.6'

env:
- ANSIBLE_VERSION=latest

before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_6135307a9f3a_key -iv $encrypted_6135307a9f3a_iv -in environment_setup/ssh/ansible.enc -out ~/.ssh/id_rsa -d
- apt-get install sshpass
- openssl aes-256-cbc -K $encrypted_907f20eb4f27_key -iv $encrypted_907f20eb4f27_iv -in environment_setup/travis.enc -out /tmp/travis -d
- PASS_PHRASE = (cat /tmp/travis)
- sshpass -p $PASS_PHRASE

install:
- if [ "$ANSIBLE_VERSION" = "latest"]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
  
script:
- cd environment_setup
- ansible-playbook -i playbook.yml --syntax-check
- ansible-playbook -i playbook.yml -vvvv

