language: python
python:
- '3.6'
env:
- ANSIBLE_VERSION=latest
before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_af7caec4de64_key -iv $encrypted_2f87619cb741_iv
  -in environments_setup/ssh/ansible.enc -out ~/.ssh/id_rsa -d
- sudo chmod 0600 ~/.ssh/id_rsa
- sudo apt-get install sshpass
- openssl aes-256-cbc -K $encrypted_c09c0e0d835e_key -iv $encrypted_c09c0e0d835e_iv
  -in environments_setup/travis.enc -out /tmp/travis -d
- PASS_PHRASE=(cat /tmp/travis)
- sshpass -p $PASS_PHRASE
install:
- pip install ansible
script:
- cd environments_setup
- ansible-playbook playbook.yml --syntax-check
- ansible-playbook playbook.yml -vvvv
