language: python

python:
- '3.6'
  
install:
  - pip3 install -r requirements.txt
  
scripts:
  - cd $TRAVIS_BUILD_DIR
  - python machine_learning/download_nltk_stopwords_wordnet.py
  - export PYSPARK_PYTHON=python3
