language: python
python:
- '3.6'
env:
- ANSIBLE_VERSION=latest
before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_af7caec4de64_key -iv $encrypted_2f87619cb741_iv
  -in environments_setup/ssh/ansible.enc -out ~/.ssh/id_rsa -d
- apt-get install sshpass
- openssl aes-256-cbc -K $encrypted_c09c0e0d835e_key -iv $encrypted_c09c0e0d835e_iv
  -in environments_setup/travis.enc -out /tmp/travis -d
- PASS_PHRASE = (cat /tmp/travis)
- sshpass -p $PASS_PHRASE
install:
- if [ "$ANSIBLE_VERSION" = "latest"]; then pip install ansible; else pip install
  ansible==$ANSIBLE_VERSION; fi
script:
- cd environments_setup
- ansible-playbook -i playbook.yml --syntax-check
- ansible-playbook -i playbook.yml -vvvv
