language: python
python:
- '3.6'
dist: trusty
sudo: required
stages:
  - test
  - deploy
jobs:
  include:
    - stage: test
      script: environments_setup/scripts/check_playbooks
    - stage: deploy
      script: environments_setup/scripts/setup_integration
    - stage: deploy
      script: environments_setup/scripts/setup_production
before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_af7caec4de64_key -iv $encrypted_af7caec4de64_iv
  -in environments_setup/ssh/ansible.enc -out ~/.ssh/id_rsa -d
- sudo chmod 0600 ~/.ssh/id_rsa
install:
- pip install ansible
