language: python

python:
- '2.7'

before_install:
  - openssl aes-256-cbc -K $encrypted_fedee2a0b6cd_key -iv $encrypted_fedee2a0b6cd_iv -in googleapi.enc -out $TRAVIS_BUILD_DIR/googleapi -d
  
install:
  - pip install -r requirements.txt
  
script:
  - python machine_learning/download_nltk_stopwords_wordnet.py