---
galaxy_info:
  author: Andrew Rothstein
  description: installs zookeeper
  company: BlackRock
  license:
    - MIT
  min_ansible_version: 2.0
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - jessie
  galaxy_tags:
    - zookeeper
    - consensus
    - distributed transaction processing

dependencies:
  - role: andrewrothstein.unarchive-deps
    version: v1.0.9
