- hosts: production
  roles:
    - copyFilesForVagrantAndAnsible
    - installVirtualbox
    - andrewrothstein.vagrant
    - { role: elastic.elasticsearch, es_instance_name: "node1" }
    - { role: geerlingguy.kibana, become: yes }
  tasks:
  - name: Destroy vagrant VM (if change in vagrant file detected)
    command: chdir=~/project/ vagrant destroy -f
    when: vagrantfile_edited == 1
  - name: Create vagrant's VM
    command: chdir=~/project/ vagrant up
- hosts: integration
  roles:
  - { role: elastic.elasticsearch, es_instance_name: "node1" }
  - { role: geerlingguy.kibana, become: yes }
- hosts: prod_integ
  roles:
  - copyProjectFiles
