
- set_fact:
    application_username: "{{ application_username }}"
    application_usergroup: "{{ application_username }}"
    application_userhome: "/home/{{ application_username }}/"

- name: "Create application user"
  become: yes
  user:
    name: "{{ application_username }}"
    state: present
    system: yes
    home: "{{ application_userhome }}"
