

- name: "Create application user"
  become: yes
  user:
    name: "{{ application_username }}"
    state: present
    system: yes
    home: "{{ application_userhome }}"
# Will error if user has running processes, since it only happen when created we can safely ignore when it happen
  ignore_errors: true

- name: "Copy common module"
  become: yes
  copy:
    src: "{{ playbook_dir }}/../big_coin_common_module/src/bigcoin"
    dest: "{{ application_userhome }}/"
    force: yes
    group: "{{ application_usergroup }}"
    owner: "{{ application_username }}"

- name: "Copy common scripts"
  become: yes
  copy:
    src: "{{ playbook_dir }}/../big_coin_common_module/src/deleteRealtimeData.py"
    dest: "{{ application_userhome }}/deleteRealtimeData.py"
    group: "{{ application_usergroup }}"
    owner: "{{ application_username }}"
