- hosts: prod_integ
  roles:
  - setupVars
  tasks:
  - name: copy scripts and configs
    become: yes
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      group: "{{ application_usergroup }}"
      owner: "{{ application_username }}"
    with_items:
      - { src: '../api_to_kafka/price_index_to_kafka_realtime.py', dest: '{{ application_userhome }}/price_index_to_kafka_realtime.py' }
      - { src: '../api_to_kafka/historique_to_kafka.py', dest: '{{ application_userhome }}/historique_to_kafka.py' }
      - { src: '../kafka_to_elastic/kafka_historique_to_elastic.py', dest: '{{ application_userhome }}/kafka_historique_to_elastic.py' }
      - { src: '../kafka_to_elastic/cours_bitcoin_realtime/target/sparkStream-1.0.jar', dest: '{{ application_userhome }}/sparkStream-1.0.jar' }
      - { src: '../pm2_configs/cours_bitcoin.config.js', dest: '{{ application_userhome }}/cours_bitcoin.config.js' }
  - name: ensure that pip is already installed
    apt: name=python-pip state=latest
    become: yes
  - name: install necessary python modules
    pip: name={{ item }} extra_args="--no-cache-dir"
    with_items:
      - elasticsearch
      - kafka
      - requests
      - pyspark
  - name: run cours_bitcoin scripts with pm2
    command: chdir="{{ application_userhome }}" su -c 'pm2 startOrReload cours_bitcoin.config.js' -s /bin/sh {{ application_username }}
    become: yes
