- hosts: prod_integ
  tasks:
  - name: copy python scripts
    copy:
      src: {{ item.src }} dest: {{ item.dest }}
      with_items:
        - { src: '../kafka_to_elastic/price_index_to_kafka_realtime.py', dest: 'project/price_index_to_kafka_realtime.py' }
  - name: ensure that pip is already installed
    apt: name=python-pip state=latest
    become: yes
  - name: install python packages elasticsearch requests pyspark
    pip: name={{ item }}
    with_items:
      - elasticsearch
      - kafka
      - requests
      - pyspark
  - name: run python scripts
    command: python "{{ item.filename }}" {{ item.args }}
    with_items:
      - { filename: "project/price_index_to_kafka_realtime.py" args: ""}
